-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 09:02:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CESI-Eats
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CESI-Eats
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CESI-EatsMysql` DEFAULT CHARACTER SET utf8 ;
USE `CESI-EatsMysql` ;

-- -----------------------------------------------------
-- Table `CESI-Eats`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CESI-EatsMysql`.`client` (
  `id_person` INT NOT NULL,
  `code_parrainage` VARCHAR(50) NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CESI-Eats`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CESI-EatsMysql`.`payments` (
  `id_payments` INT NOT NULL,
  `card_number` VARCHAR(45) NULL,
  `owner_name` VARCHAR(45) NULL,
  `expiration_date` VARCHAR(45) NULL,
  `cvv` VARCHAR(45) NULL,
  PRIMARY KEY (`id_payments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CESI-Eats`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CESI-EatsMysql`.`address` (
  `id_address` INT NOT NULL,
  `country` VARCHAR(200) NULL,
  `postcode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CESI-Eats`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CESI-EatsMysql`.`person` (
  `id_person` INT NOT NULL,
  `surname` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `birth` DATE NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(45) NULL,
  `address` INT NULL,
  `personcol` VARCHAR(45) NULL,
  `payments_informations` INT NULL,
  `password` VARCHAR(45) NULL,
  `role` INT NULL,
  PRIMARY KEY (`id_person`),
  INDEX `payments_informations_idx` (`payments_informations` ASC) VISIBLE,
  INDEX `address_idx` (`address` ASC) VISIBLE,
  CONSTRAINT `payments_informations`
    FOREIGN KEY (`payments_informations`)
    REFERENCES `CESI-Eats`.`payments` (`id_payments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `address`
    FOREIGN KEY (`address`)
    REFERENCES `CESI-EatsMysql`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CESI-Eats`.`restaurateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CESI-EatsMysql`.`restaurateur` (
  `id_restaurant` INT NOT NULL,
  `code_parrainage` VARCHAR(45) NULL,
  `restaurant_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_restaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CESI-Eats`.`deliverer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CESI-EatsMysql`.`deliverer` (
  `id_person` INT NOT NULL,
  `statut_activite` TINYINT NULL,
  `code_parrainage` VARCHAR(45) NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CESI-Eats`.`developer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CESI-EatsMysql`.`developer` (
  `id_person` INT NOT NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
